"""
MCOC Champion Tier List Data
Aggregated from YouTube creators: KT1, Lagacy, Vega, MGuideBlog, Omega
Source: Summoner's Tier List community spreadsheet (last updated Dec 2025)
"""

RAW_CHAMPIONS = {
    # ===== COSMIC =====
    "Hulkling": {"class": "Cosmic", "score": 100, "awakened": False},
    "Karolina Dean": {"class": "Cosmic", "score": 100, "awakened": False},
    "Thanos (Deathless)": {"class": "Cosmic", "score": 100, "awakened": False},
    "The Serpent": {"class": "Cosmic", "score": 100, "awakened": True},
    "Cull Obsidian": {"class": "Cosmic", "score": 91, "awakened": True},
    "Cosmic Ghost Rider": {"class": "Cosmic", "score": 90, "awakened": True, "no7star": True},
    "Hercules": {"class": "Cosmic", "score": 90, "awakened": True, "no7star": True},
    "Galan": {"class": "Cosmic", "score": 86, "awakened": False},
    "Medusa": {"class": "Cosmic", "score": 81, "awakened": True},
    "Venom": {"class": "Cosmic", "score": 81, "awakened": False},
    "Dark Phoenix": {"class": "Cosmic", "score": 80, "awakened": True},
    "Hyperion": {"class": "Cosmic", "score": 78, "awakened": True},
    "Adam Warlock": {"class": "Cosmic", "score": 76, "awakened": False},
    "Scream": {"class": "Cosmic", "score": 76, "awakened": True},
    "Imperiosa": {"class": "Cosmic", "score": 73, "awakened": False},
    "Vox": {"class": "Cosmic", "score": 73, "awakened": True},
    "Knull": {"class": "Cosmic", "score": 72, "awakened": True},
    "Gladiator": {"class": "Cosmic", "score": 71, "awakened": False},
    "Angela": {"class": "Cosmic", "score": 69, "awakened": True},
    "Corvus Glaive": {"class": "Cosmic", "score": 68, "awakened": True},
    "Beta Ray Bill": {"class": "Cosmic", "score": 67, "awakened": True},
    "Venom the Duck": {"class": "Cosmic", "score": 67, "awakened": False},
    "Odin": {"class": "Cosmic", "score": 65, "awakened": False},
    "Superior Iron Man": {"class": "Cosmic", "score": 63, "awakened": False},
    "Captain Marvel (Movie)": {"class": "Cosmic", "score": 57, "awakened": True},
    "Maestro": {"class": "Cosmic", "score": 57, "awakened": True},
    "Phoenix": {"class": "Cosmic", "score": 57, "awakened": True},
    "Gamora": {"class": "Cosmic", "score": 54, "awakened": False},
    "King Groot": {"class": "Cosmic", "score": 54, "awakened": True, "no7star": True},
    "Venompool": {"class": "Cosmic", "score": 54, "awakened": True},
    "King Groot (Deathless)": {"class": "Cosmic", "score": 50, "awakened": True},
    "Gorr": {"class": "Cosmic", "score": 48, "awakened": False},
    "Vision (Aarkus)": {"class": "Cosmic", "score": 45, "awakened": False},
    "Nova": {"class": "Cosmic", "score": 43, "awakened": True},
    "Sersi": {"class": "Cosmic", "score": 43, "awakened": False},
    "Terrax": {"class": "Cosmic", "score": 38, "awakened": True},
    "Carnage": {"class": "Cosmic", "score": 38, "awakened": True},
    "Silver Surfer": {"class": "Cosmic", "score": 38, "awakened": True},
    "Super-Skrull": {"class": "Cosmic", "score": 33, "awakened": False},
    "Ronan": {"class": "Cosmic", "score": 29, "awakened": True, "no7star": True},
    "Hela": {"class": "Cosmic", "score": 27, "awakened": False, "no7star": True},
    "Proxima Midnight": {"class": "Cosmic", "score": 27, "awakened": True, "no7star": True},
    "Heimdall": {"class": "Cosmic", "score": 23, "awakened": False},
    "Ikaris": {"class": "Cosmic", "score": 23, "awakened": False, "no7star": True},
    "Red Goblin": {"class": "Cosmic", "score": 23, "awakened": True},
    "Thor": {"class": "Cosmic", "score": 23, "awakened": True, "no7star": True},
    "Black Bolt": {"class": "Cosmic", "score": 19, "awakened": True, "no7star": True},
    "Annihilus": {"class": "Cosmic", "score": 18, "awakened": False, "no7star": True},
    "The Champion": {"class": "Cosmic", "score": 18, "awakened": False, "no7star": True},
    "Spider-Man (Symbiote)": {"class": "Cosmic", "score": 13, "awakened": False, "no7star": True},
    "Captain Marvel (Classic)": {"class": "Cosmic", "score": 8, "awakened": False, "no7star": True},
    "Ms. Marvel (OG)": {"class": "Cosmic", "score": 8, "awakened": False, "no7star": True},
    "Air-Walker": {"class": "Cosmic", "score": 4, "awakened": False, "no7star": True},
    "Ms. Marvel (Kamala)": {"class": "Cosmic", "score": 4, "awakened": True, "no7star": True},
    "Drax": {"class": "Cosmic", "score": 0, "awakened": False, "no7star": True},
    "Groot": {"class": "Cosmic", "score": 0, "awakened": False, "no7star": True},
    "Thanos": {"class": "Cosmic", "score": 0, "awakened": False, "no7star": True},

    # ===== MUTANT =====
    "Jean Grey": {"class": "Mutant", "score": 100, "awakened": True},
    "Mister Sinister": {"class": "Mutant", "score": 100, "awakened": True},
    "Onslaught": {"class": "Mutant", "score": 100, "awakened": False},
    "Dazzler": {"class": "Mutant", "score": 90, "awakened": True},
    "Deadpool (X-Force)": {"class": "Mutant", "score": 90, "awakened": False},
    "Archangel": {"class": "Mutant", "score": 86, "awakened": True, "no7star": True},
    "Kitty Pryde": {"class": "Mutant", "score": 85, "awakened": True},
    "Cyclops (Blue Team)": {"class": "Mutant", "score": 83, "awakened": False},
    "Magneto (Red)": {"class": "Mutant", "score": 81, "awakened": False, "no7star": True},
    "Gentle": {"class": "Mutant", "score": 78, "awakened": False},
    "Apocalypse": {"class": "Mutant", "score": 77, "awakened": False},
    "Omega Red": {"class": "Mutant", "score": 73, "awakened": True},
    "Negasonic": {"class": "Mutant", "score": 72, "awakened": True},
    "Domino": {"class": "Mutant", "score": 71, "awakened": False},
    "Silver Samurai": {"class": "Mutant", "score": 71, "awakened": False},
    "Havok": {"class": "Mutant", "score": 69, "awakened": False},
    "Professor X": {"class": "Mutant", "score": 69, "awakened": True},
    "Dust": {"class": "Mutant", "score": 67, "awakened": True},
    "Captain Britain": {"class": "Mutant", "score": 66, "awakened": True},
    "Storm (OG)": {"class": "Mutant", "score": 64, "awakened": False},
    "Bishop": {"class": "Mutant", "score": 63, "awakened": False},
    "Cassandra Nova": {"class": "Mutant", "score": 62, "awakened": False},
    "Colossus": {"class": "Mutant", "score": 62, "awakened": True},
    "Sunspot": {"class": "Mutant", "score": 62, "awakened": False},
    "Wolverine (Weapon X)": {"class": "Mutant", "score": 59, "awakened": True},
    "Namor": {"class": "Mutant", "score": 57, "awakened": True},
    "Nightcrawler": {"class": "Mutant", "score": 57, "awakened": False},
    "Wolverine (X-23)": {"class": "Mutant", "score": 56, "awakened": False},
    "Dani Moonstar": {"class": "Mutant", "score": 52, "awakened": True},
    "Toad": {"class": "Mutant", "score": 50, "awakened": True, "no7star": True},
    "Emma Frost": {"class": "Mutant", "score": 48, "awakened": False},
    "Iceman": {"class": "Mutant", "score": 48, "awakened": True},
    "Stryfe": {"class": "Mutant", "score": 48, "awakened": True},
    "Northstar": {"class": "Mutant", "score": 47, "awakened": False},
    "Magneto (House of X)": {"class": "Mutant", "score": 43, "awakened": True, "no7star": True},
    "Storm (Pyramid X)": {"class": "Mutant", "score": 43, "awakened": False},
    "Gambit": {"class": "Mutant", "score": 38, "awakened": False},
    "Sabretooth": {"class": "Mutant", "score": 37, "awakened": False},
    "Sauron": {"class": "Mutant", "score": 33, "awakened": False},
    "Wolverine (OG)": {"class": "Mutant", "score": 28, "awakened": True, "no7star": True},
    "Cable": {"class": "Mutant", "score": 19, "awakened": False, "no7star": True},
    "Jubilee": {"class": "Mutant", "score": 18, "awakened": False, "no7star": True},
    "Old Man Logan": {"class": "Mutant", "score": 18, "awakened": True, "no7star": True},
    "Rogue": {"class": "Mutant", "score": 18, "awakened": True, "no7star": True},
    "Psylocke": {"class": "Mutant", "score": 14, "awakened": True, "no7star": True},
    "Platinumpool": {"class": "Mutant", "score": 10, "awakened": False},
    "Beast": {"class": "Mutant", "score": 0, "awakened": False, "no7star": True},
    "Cyclops (New Xavier School)": {"class": "Mutant", "score": 0, "awakened": False, "no7star": True},
    "Deadpool": {"class": "Mutant", "score": 0, "awakened": False, "no7star": True},
    "Goldpool": {"class": "Mutant", "score": 0, "awakened": False, "no7star": True},

    # ===== MYSTIC =====
    "Kushala": {"class": "Mystic", "score": 100, "awakened": True},
    "Nico Minoru": {"class": "Mystic", "score": 100, "awakened": True},
    "Spider-Man (Pavitr)": {"class": "Mystic", "score": 100, "awakened": True},
    "Absorbing Man": {"class": "Mystic", "score": 96, "awakened": True},
    "Shathra": {"class": "Mystic", "score": 96, "awakened": True},
    "Juggernaut": {"class": "Mystic", "score": 95, "awakened": True},
    "Tigra": {"class": "Mystic", "score": 91, "awakened": True},
    "Doctor Doom": {"class": "Mystic", "score": 90, "awakened": False, "no7star": True},
    "America Chavez": {"class": "Mystic", "score": 88, "awakened": True},
    "The Hood": {"class": "Mystic", "score": 83, "awakened": True},
    "Purgatory": {"class": "Mystic", "score": 82, "awakened": True},
    "Werewolf By Night": {"class": "Mystic", "score": 79, "awakened": False},
    "Rintrah": {"class": "Mystic", "score": 73, "awakened": False},
    "Spiral": {"class": "Mystic", "score": 72, "awakened": False},
    "Black Widow (Claire Voyant)": {"class": "Mystic", "score": 69, "awakened": False, "no7star": True},
    "Diablo": {"class": "Mystic", "score": 67, "awakened": True},
    "Symbiote Supreme": {"class": "Mystic", "score": 67, "awakened": False},
    "White Tiger": {"class": "Mystic", "score": 67, "awakened": False},
    "Longshot": {"class": "Mystic", "score": 66, "awakened": False},
    "Wiccan": {"class": "Mystic", "score": 62, "awakened": True},
    "Magik": {"class": "Mystic", "score": 61, "awakened": True, "no7star": True},
    "Mojo": {"class": "Mystic", "score": 60, "awakened": True},
    "Scarlet Witch (Sigil)": {"class": "Mystic", "score": 59, "awakened": False},
    "Thor (Jane Foster)": {"class": "Mystic", "score": 59, "awakened": False},
    "Doctor Voodoo": {"class": "Mystic", "score": 55, "awakened": True},
    "Scarlet Witch (Classic)": {"class": "Mystic", "score": 54, "awakened": True},
    "Spider-Man (Supreme)": {"class": "Mystic", "score": 53, "awakened": True},
    "Enchantress": {"class": "Mystic", "score": 51, "awakened": True},
    "Kindred": {"class": "Mystic", "score": 51, "awakened": True},
    "Wong": {"class": "Mystic", "score": 50, "awakened": False},
    "Sasquatch": {"class": "Mystic", "score": 49, "awakened": True},
    "Isophyne": {"class": "Mystic", "score": 48, "awakened": True},
    "Sorcerer Supreme": {"class": "Mystic", "score": 48, "awakened": False},
    "The Destroyer": {"class": "Mystic", "score": 48, "awakened": True},
    "Mordo": {"class": "Mystic", "score": 46, "awakened": False},
    "Dracula": {"class": "Mystic", "score": 39, "awakened": False},
    "Dragon Man": {"class": "Mystic", "score": 38, "awakened": False},
    "Guillotine": {"class": "Mystic", "score": 36, "awakened": False, "no7star": True},
    "Ebony Maw": {"class": "Mystic", "score": 33, "awakened": False},
    "Mephisto": {"class": "Mystic", "score": 33, "awakened": False, "no7star": True},
    "Man-Thing": {"class": "Mystic", "score": 29, "awakened": False},
    "Guillotine (Deathless)": {"class": "Mystic", "score": 27, "awakened": False},
    "Doctor Strange": {"class": "Mystic", "score": 20, "awakened": True, "no7star": True},
    "Morningstar": {"class": "Mystic", "score": 18, "awakened": True, "no7star": True},
    "Mangog": {"class": "Mystic", "score": 15, "awakened": False},
    "Ghost Rider": {"class": "Mystic", "score": 14, "awakened": True, "no7star": True},
    "Loki": {"class": "Mystic", "score": 9, "awakened": False, "no7star": True},
    "Dormammu": {"class": "Mystic", "score": 5, "awakened": False, "no7star": True},
    "Iron Fist (Immortal)": {"class": "Mystic", "score": 0, "awakened": False, "no7star": True},
    "Iron Fist": {"class": "Mystic", "score": 0, "awakened": False, "no7star": True},
    "Unstoppable Colossus": {"class": "Mystic", "score": 0, "awakened": False, "no7star": True},

    # ===== SCIENCE =====
    "Count Nefaria": {"class": "Science", "score": 100, "awakened": True},
    "Photon": {"class": "Science", "score": 100, "awakened": True},
    "Spider-Woman (Jessica Drew)": {"class": "Science", "score": 100, "awakened": False},
    "Human Torch": {"class": "Science", "score": 96, "awakened": False},
    "Scorpion": {"class": "Science", "score": 96, "awakened": False},
    "Silk": {"class": "Science", "score": 93, "awakened": True},
    "Red Guardian": {"class": "Science", "score": 88, "awakened": True},
    "Hulk (OG)": {"class": "Science", "score": 83, "awakened": True},
    "Spider-Ham": {"class": "Science", "score": 81, "awakened": False},
    "Luke Cage": {"class": "Science", "score": 79, "awakened": True},
    "Anti-Venom": {"class": "Science", "score": 77, "awakened": True},
    "Cassie Lang": {"class": "Science", "score": 72, "awakened": True},
    "Void": {"class": "Science", "score": 72, "awakened": True},
    "Titania": {"class": "Science", "score": 71, "awakened": True},
    "She-Hulk (Deathless)": {"class": "Science", "score": 70, "awakened": False},
    "Lizard": {"class": "Science", "score": 68, "awakened": False},
    "Spot": {"class": "Science", "score": 67, "awakened": True},
    "Quicksilver": {"class": "Science", "score": 65, "awakened": True},
    "She-Hulk": {"class": "Science", "score": 64, "awakened": True},
    "Spider-Punk": {"class": "Science", "score": 63, "awakened": True},
    "Quake": {"class": "Science", "score": 61, "awakened": False, "no7star": True},
    "Spider-Man 2099": {"class": "Science", "score": 60, "awakened": True},
    "The Overseer": {"class": "Science", "score": 60, "awakened": True},
    "Peni Parker": {"class": "Science", "score": 60, "awakened": True},
    "Abomination (Immortal)": {"class": "Science", "score": 58, "awakened": True},
    "Sentry": {"class": "Science", "score": 57, "awakened": True},
    "High Evolutionary": {"class": "Science", "score": 56, "awakened": True},
    "The Leader": {"class": "Science", "score": 51, "awakened": False},
    "Mister Negative": {"class": "Science", "score": 50, "awakened": True},
    "Captain America (Infinity War)": {"class": "Science", "score": 49, "awakened": True},
    "Morbius": {"class": "Science", "score": 48, "awakened": False},
    "Mister Fantastic": {"class": "Science", "score": 46, "awakened": True},
    "Sandman": {"class": "Science", "score": 46, "awakened": True},
    "Hulk (Immortal)": {"class": "Science", "score": 45, "awakened": False},
    "Joe Fixit": {"class": "Science", "score": 43, "awakened": False},
    "Spider-Gwen": {"class": "Science", "score": 43, "awakened": True},
    "Jessica Jones": {"class": "Science", "score": 42, "awakened": False},
    "Spider-Man (Miles Morales)": {"class": "Science", "score": 42, "awakened": True},
    "M.O.D.O.K.": {"class": "Science", "score": 37, "awakened": False},
    "Thing": {"class": "Science", "score": 37, "awakened": True},
    "Ant-Man": {"class": "Science", "score": 34, "awakened": True},
    "Rhino": {"class": "Science", "score": 33, "awakened": False},
    "Spider-Man (Classic)": {"class": "Science", "score": 31, "awakened": True},
    "Falcon (Joaquin Torres)": {"class": "Science", "score": 28, "awakened": True},
    "Red Hulk": {"class": "Science", "score": 28, "awakened": False},
    "Iron Man (Infinity War)": {"class": "Science", "score": 28, "awakened": False},
    "Hulk (Ragnarok)": {"class": "Science", "score": 23, "awakened": False, "no7star": True},
    "Wasp": {"class": "Science", "score": 23, "awakened": False, "no7star": True},
    "Invisible Woman": {"class": "Science", "score": 19, "awakened": False},
    "Yellowjacket": {"class": "Science", "score": 18, "awakened": True, "no7star": True},
    "Electro": {"class": "Science", "score": 14, "awakened": True, "no7star": True},
    "Abomination": {"class": "Science", "score": 9, "awakened": False, "no7star": True},
    "Captain America (Classic)": {"class": "Science", "score": 0, "awakened": False, "no7star": True},
    "Captain America (WWII)": {"class": "Science", "score": 0, "awakened": False, "no7star": True},

    # ===== SKILL =====
    "Okoye": {"class": "Skill", "score": 100, "awakened": True},
    "Nick Fury": {"class": "Skill", "score": 98, "awakened": True},
    "Kingpin": {"class": "Skill", "score": 91, "awakened": True},
    "Kate Bishop": {"class": "Skill", "score": 90, "awakened": True, "no7star": True},
    "Chee'ilth": {"class": "Skill", "score": 88, "awakened": True},
    "Shang-Chi": {"class": "Skill", "score": 88, "awakened": False},
    "Crossbones": {"class": "Skill", "score": 86, "awakened": True},
    "Bullseye": {"class": "Skill", "score": 81, "awakened": False},
    "Valkyrie": {"class": "Skill", "score": 81, "awakened": True},
    "Mr. Knight": {"class": "Skill", "score": 77, "awakened": False},
    "Lumatrix": {"class": "Skill", "score": 76, "awakened": False},
    "Mole Man": {"class": "Skill", "score": 76, "awakened": False},
    "Mantis": {"class": "Skill", "score": 73, "awakened": False},
    "Baron Zemo": {"class": "Skill", "score": 72, "awakened": False},
    "Spider-Man (Stealth Suit)": {"class": "Skill", "score": 72, "awakened": True},
    "Hit-Monkey": {"class": "Skill", "score": 71, "awakened": False},
    "Black Cat": {"class": "Skill", "score": 67, "awakened": True},
    "Franken-Castle": {"class": "Skill", "score": 67, "awakened": False},
    "Aegon": {"class": "Skill", "score": 61, "awakened": True},
    "Punisher": {"class": "Skill", "score": 60, "awakened": False},
    "Masacre": {"class": "Skill", "score": 57, "awakened": True},
    "Silver Sable": {"class": "Skill", "score": 53, "awakened": False},
    "Black Panther (Civil War)": {"class": "Skill", "score": 53, "awakened": False},
    "Blade": {"class": "Skill", "score": 50, "awakened": True},
    "Jabari Panther": {"class": "Skill", "score": 50, "awakened": True},
    "Attuma": {"class": "Skill", "score": 48, "awakened": False},
    "Moondragon": {"class": "Skill", "score": 48, "awakened": True},
    "Elsa Bloodstone": {"class": "Skill", "score": 45, "awakened": True},
    "Black Widow (Deadly Origin)": {"class": "Skill", "score": 43, "awakened": False},
    "Ronin": {"class": "Skill", "score": 41, "awakened": True},
    "Black Panther (Classic)": {"class": "Skill", "score": 40, "awakened": True},
    "Patriot": {"class": "Skill", "score": 40, "awakened": True},
    "Killmonger": {"class": "Skill", "score": 38, "awakened": True},
    "Hawkeye": {"class": "Skill", "score": 33, "awakened": True},
    "Karnak": {"class": "Skill", "score": 31, "awakened": True, "no7star": True},
    "Korg": {"class": "Skill", "score": 28, "awakened": False},
    "Night Thrasher": {"class": "Skill", "score": 28, "awakened": True},
    "Gwenpool": {"class": "Skill", "score": 28, "awakened": True},
    "Thor (Ragnarok)": {"class": "Skill", "score": 28, "awakened": True, "no7star": True},
    "Agent Venom": {"class": "Skill", "score": 27, "awakened": False, "no7star": True},
    "Daredevil (Hell's Kitchen)": {"class": "Skill", "score": 23, "awakened": True},
    "Misty Knight": {"class": "Skill", "score": 23, "awakened": False},
    "Squirrel Girl": {"class": "Skill", "score": 23, "awakened": True, "no7star": True},
    "Kraven": {"class": "Skill", "score": 14, "awakened": True},
    "Black Widow (OG)": {"class": "Skill", "score": 9, "awakened": True, "no7star": True},
    "Taskmaster": {"class": "Skill", "score": 9, "awakened": True, "no7star": True},
    "Winter Soldier": {"class": "Skill", "score": 4, "awakened": False, "no7star": True},
    "Daredevil (Classic)": {"class": "Skill", "score": 0, "awakened": False, "no7star": True},
    "Elektra": {"class": "Skill", "score": 0, "awakened": False, "no7star": True},
    "Moon Knight": {"class": "Skill", "score": 0, "awakened": False, "no7star": True},

    # ===== TECH =====
    "Ant-Man (Future)": {"class": "Tech", "score": 100, "awakened": True},
    "Bastion": {"class": "Tech", "score": 100, "awakened": False},
    "Spider-Man (Stark Enhanced)": {"class": "Tech", "score": 93, "awakened": True},
    "Nimrod": {"class": "Tech", "score": 91, "awakened": True},
    "Jack O'Lantern": {"class": "Tech", "score": 90, "awakened": False},
    "Arnim Zola": {"class": "Tech", "score": 87, "awakened": False},
    "Ghost": {"class": "Tech", "score": 86, "awakened": True, "no7star": True},
    "Sentinel": {"class": "Tech", "score": 82, "awakened": True},
    "Guardian": {"class": "Tech", "score": 81, "awakened": True},
    "Prowler": {"class": "Tech", "score": 81, "awakened": False},
    "Ironheart": {"class": "Tech", "score": 79, "awakened": True},
    "Warlock": {"class": "Tech", "score": 78, "awakened": False},
    "Shuri": {"class": "Tech", "score": 78, "awakened": False},
    "Solvarch": {"class": "Tech", "score": 77, "awakened": False},
    "Shocker": {"class": "Tech", "score": 73, "awakened": True},
    "Red Skull": {"class": "Tech", "score": 73, "awakened": False},
    "Viv Vision": {"class": "Tech", "score": 73, "awakened": True},
    "The Maker": {"class": "Tech", "score": 72, "awakened": True},
    "Iron Man (OG)": {"class": "Tech", "score": 69, "awakened": False},
    "Ultron (Prime)": {"class": "Tech", "score": 67, "awakened": True},
    "Guillotine 2099": {"class": "Tech", "score": 65, "awakened": False},
    "Omega Sentinel": {"class": "Tech", "score": 65, "awakened": True},
    "Hulkbuster": {"class": "Tech", "score": 64, "awakened": False},
    "Peni Parker": {"class": "Tech", "score": 60, "awakened": True},
    "Yondu": {"class": "Tech", "score": 58, "awakened": False},
    "Iron Man (Infamous)": {"class": "Tech", "score": 53, "awakened": False},
    "Lady Deathstrike": {"class": "Tech", "score": 53, "awakened": True},
    "Nebula": {"class": "Tech", "score": 51, "awakened": False, "no7star": True},
    "Punisher 2099": {"class": "Tech", "score": 48, "awakened": True},
    "Arcade": {"class": "Tech", "score": 48, "awakened": False},
    "Howard the Duck": {"class": "Tech", "score": 48, "awakened": False},
    "Mysterio": {"class": "Tech", "score": 43, "awakened": False},
    "Rocket Raccoon": {"class": "Tech", "score": 38, "awakened": True},
    "Captain America (Sam Wilson)": {"class": "Tech", "score": 33, "awakened": True},
    "Darkhawk": {"class": "Tech", "score": 33, "awakened": True, "no7star": True},
    "Doctor Octopus": {"class": "Tech", "score": 33, "awakened": True, "no7star": True},
    "War Machine": {"class": "Tech", "score": 31, "awakened": False},
    "Iron Man (Infinity War)": {"class": "Tech", "score": 28, "awakened": False},
    "Vision (Deathless)": {"class": "Tech", "score": 27, "awakened": False},
    "Star-Lord": {"class": "Tech", "score": 23, "awakened": True, "no7star": True},
    "Vision (Age of Ultron)": {"class": "Tech", "score": 19, "awakened": True, "no7star": True},
    "Vision (Classic)": {"class": "Tech", "score": 19, "awakened": True},
    "Silver Centurion": {"class": "Tech", "score": 14, "awakened": True, "no7star": True},
    "Vulture": {"class": "Tech", "score": 14, "awakened": False, "no7star": True},
    "Civil Warrior": {"class": "Tech", "score": 13, "awakened": True},
    "Ultron (Classic)": {"class": "Tech", "score": 10, "awakened": False},
    "Green Goblin": {"class": "Tech", "score": 9, "awakened": False, "no7star": True},
    "Psycho-Man": {"class": "Tech", "score": 4, "awakened": True, "no7star": True},
    "Iron Patriot": {"class": "Tech", "score": 0, "awakened": False, "no7star": True},
    "Kang": {"class": "Tech", "score": 0, "awakened": False, "no7star": True},
}

SOURCES = [
    {"name": "KT1", "type": "YouTube"},
    {"name": "Lagacy", "type": "YouTube"},
    {"name": "Vega", "type": "YouTube"},
    {"name": "MGuideBlog", "type": "YouTube"},
    {"name": "Omega", "type": "YouTube"},
]

CLASS_COLORS = {
    "Cosmic": "#3b82f6",
    "Tech": "#6366f1",
    "Mutant": "#eab308",
    "Skill": "#ef4444",
    "Science": "#22c55e",
    "Mystic": "#a855f7",
}


def score_to_tier(score: int) -> str:
    if score >= 90:
        return "God"
    if score >= 70:
        return "Great"
    if score >= 50:
        return "Good"
    if score >= 30:
        return "OK"
    return "Low"


TIER_COLORS = {
    "God": "#f59e0b",
    "Great": "#3b82f6",
    "Good": "#22c55e",
    "OK": "#9ca3af",
    "Low": "#6b7280",
}


def compute_tier_list():
    champions = []
    for name, data in RAW_CHAMPIONS.items():
        tier = score_to_tier(data["score"])
        champions.append({
            "name": name,
            "class": data["class"],
            "tier": tier,
            "score": data["score"],
            "awakened": data["awakened"],
            "no7star": data.get("no7star", False),
        })

    champions.sort(key=lambda c: (-c["score"], c["name"]))
    for i, champ in enumerate(champions):
        champ["rank"] = i + 1

    return champions


def get_champions_by_class(champions):
    by_class = {}
    for champ in champions:
        cls = champ["class"]
        if cls not in by_class:
            by_class[cls] = []
        by_class[cls].append(champ)

    for cls in by_class:
        by_class[cls].sort(key=lambda c: (-c["score"], c["name"]))
        for i, champ in enumerate(by_class[cls]):
            champ["class_rank"] = i + 1

    return by_class
