"""
Champion immunity data aggregated from Fandom wiki category pages.
Only includes always-active or near-always-active immunities.
Excludes synergy-only and heavily conditional immunities.
"""

IMMUNITY_TYPES = [
    "Bleed",
    "Poison",
    "Incinerate",
    "Shock",
    "Coldsnap",
    "Frostbite",
    "Nullify",
    "Stagger",
    "Armor Break",
    "Fate Seal",
]

# Champions mapped to their immunities
CHAMPION_IMMUNITIES = {
    "Abomination": ["Poison"],
    "Abomination (Immortal)": ["Poison"],
    "Absorbing Man": ["Armor Break"],
    "Adam Warlock": ["Nullify", "Stagger", "Fate Seal"],
    "Annihilus": ["Coldsnap", "Frostbite", "Incinerate"],
    "Ant-Man": ["Poison", "Shock"],
    "Anti-Venom": ["Incinerate"],
    "Arnim Zola": ["Bleed", "Poison"],
    "Beta Ray Bill": ["Shock"],
    "Black Bolt": ["Poison"],
    "Black Widow (Claire Voyant)": ["Bleed", "Incinerate"],
    "Blue Marvel": ["Bleed"],
    "Captain Marvel (Classic)": ["Poison"],
    "Captain Marvel (Movie)": ["Poison"],
    "Cassie Lang": ["Shock"],
    "Civil Warrior": ["Nullify", "Stagger"],
    "Colossus": ["Bleed", "Incinerate", "Coldsnap", "Frostbite", "Armor Break"],
    "Cosmic Ghost Rider": ["Bleed", "Incinerate"],
    "Count Nefaria": ["Bleed"],
    "Crossbones": ["Nullify", "Stagger"],
    "Dark Phoenix": ["Incinerate"],
    "Darkhawk": ["Bleed", "Poison"],
    "Doctor Doom": ["Shock", "Armor Break"],
    "Dormammu": ["Bleed", "Poison"],
    "Dragon Man": ["Bleed"],
    "Dust": ["Bleed", "Poison", "Shock"],
    "Electro": ["Shock"],
    "Franken-Castle": ["Poison"],
    "Galan": ["Nullify", "Fate Seal"],
    "Gentle": ["Bleed"],
    "Ghost Rider": ["Bleed", "Incinerate"],
    "Groot": ["Bleed"],
    "Guillotine 2099": ["Bleed", "Poison"],
    "Havok": ["Incinerate"],
    "Heimdall": ["Fate Seal"],
    "Howard the Duck": ["Bleed"],
    "Hulk": ["Poison"],
    "Hulk (Immortal)": ["Poison"],
    "Hulk (Ragnarok)": ["Poison"],
    "Hulkling": ["Shock"],
    "Human Torch": ["Incinerate", "Coldsnap", "Frostbite"],
    "Hyperion": ["Poison"],
    "Iceman": ["Bleed", "Poison", "Incinerate"],
    "Ikaris": ["Incinerate", "Shock"],
    "Imperiosa": ["Bleed"],
    "Iron Man (Infinity War)": ["Bleed"],
    "Isophyne": ["Bleed", "Coldsnap", "Frostbite"],
    "Jack O'Lantern": ["Incinerate"],
    "Joe Fixit": ["Poison"],
    "Karolina Dean": ["Coldsnap", "Frostbite"],
    "Kindred": ["Incinerate"],
    "King Groot": ["Bleed"],
    "King Groot (Deathless)": ["Bleed"],
    "Kitty Pryde": ["Incinerate"],
    "Korg": ["Bleed", "Shock"],
    "Kushala": ["Bleed", "Incinerate"],
    "Lizard": ["Poison"],
    "Luke Cage": ["Bleed"],
    "Lumatrix": ["Bleed"],
    "M'Baku": ["Frostbite"],
    "Magneto (House of X)": ["Bleed"],
    "Man-Thing": ["Bleed", "Armor Break"],
    "Mangog": ["Bleed", "Armor Break"],
    "Medusa": ["Poison"],
    "Mephisto": ["Incinerate", "Coldsnap", "Frostbite"],
    "Mister Negative": ["Nullify", "Stagger", "Fate Seal"],
    "Mole Man": ["Shock"],
    "Morningstar": ["Bleed"],
    "Ms. Marvel": ["Poison"],
    "Ms. Marvel (Kamala Khan)": ["Poison"],
    "Mysterio": ["Poison"],
    "Nebula": ["Bleed", "Poison"],
    "Night Thrasher": ["Incinerate"],
    "Nimrod": ["Bleed"],
    "Omega Red": ["Poison"],
    "Omega Sentinel": ["Bleed", "Poison", "Nullify", "Stagger", "Fate Seal"],
    "Peni Parker": ["Poison", "Incinerate"],
    "Phoenix": ["Incinerate"],
    "Photon": ["Bleed"],
    "Prowler": ["Bleed", "Incinerate"],
    "Purgatory": ["Incinerate"],
    "Red Goblin": ["Incinerate"],
    "Red Hulk": ["Poison", "Incinerate"],
    "Red Skull": ["Nullify", "Stagger", "Fate Seal"],
    "Ronan": ["Poison"],
    "Sabretooth": ["Coldsnap", "Frostbite"],
    "Sandman": ["Bleed", "Poison", "Shock"],
    "Sasquatch": ["Frostbite", "Armor Break"],
    "Sauron": ["Poison"],
    "Sentinel": ["Bleed", "Poison"],
    "Sentry": ["Incinerate", "Nullify", "Fate Seal"],
    "She-Hulk": ["Poison"],
    "She-Hulk (Deathless)": ["Poison"],
    "Shocker": ["Shock"],
    "Shuri": ["Shock"],
    "Silver Surfer": ["Incinerate", "Shock", "Coldsnap", "Frostbite"],
    "Solvarch": ["Bleed", "Poison"],
    "Spider-Slayer (J. Jonah Jameson)": ["Bleed"],
    "Spider-Woman (Jessica Drew)": ["Poison"],
    "Storm": ["Shock"],
    "Storm (Pyramid X)": ["Shock", "Coldsnap", "Frostbite"],
    "Sunspot": ["Incinerate"],
    "Super-Skrull": ["Incinerate", "Shock"],
    "Terrax": ["Bleed", "Shock"],
    "Thanos (Deathless)": ["Poison", "Coldsnap", "Frostbite"],
    "The Destroyer": ["Bleed", "Poison", "Armor Break"],
    "The Leader": ["Poison"],
    "The Overseer": ["Poison", "Nullify", "Stagger", "Fate Seal"],
    "The Serpent": ["Coldsnap", "Nullify", "Stagger", "Fate Seal"],
    "Thing": ["Bleed", "Shock", "Nullify", "Stagger", "Fate Seal", "Armor Break"],
    "Toad": ["Poison"],
    "Ultron": ["Bleed", "Poison"],
    "Ultron (Classic)": ["Bleed", "Poison"],
    "Unstoppable Colossus": ["Bleed"],
    "Vision": ["Bleed", "Poison"],
    "Vision (Age of Ultron)": ["Bleed", "Poison"],
    "Viv Vision": ["Bleed", "Poison"],
    "Void": ["Incinerate"],
    "Vox": ["Poison"],
    "Vulture": ["Poison", "Incinerate", "Shock"],
    "Warlock": ["Bleed", "Incinerate", "Coldsnap", "Frostbite"],
    "X-23 (Orochi)": ["Bleed"],
}


def get_immunities_for_champion(name: str) -> list[str]:
    return CHAMPION_IMMUNITIES.get(name, [])


def get_champions_by_immunity(immunity_type: str) -> list[str]:
    return sorted([
        name for name, immunities in CHAMPION_IMMUNITIES.items()
        if immunity_type in immunities
    ])


def get_immunity_map() -> dict[str, list[str]]:
    """Returns {immunity_type: [champion_names]}"""
    result = {}
    for imm_type in IMMUNITY_TYPES:
        result[imm_type] = get_champions_by_immunity(imm_type)
    return result
